name: Output Information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github)}}
          #https://github.com/actions/runner/issues/1656